//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eticaretproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        public int Id { get; set; }
        public string Tanim { get; set; }
        public Nullable<int> UstkategoriId { get; set; }
    }
}
